FROM node:22-alpine as build

WORKDIR /usr/src/app

# Install dependencies before copying the rest of the app, so that
# this step can be cached.
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the project.
COPY . ./

# Make a production build
RUN npm run build

# Run in a separate stage that isn't bloated with our dependencies
FROM node:22-alpine

ARG VITE_API_HOST
ENV VITE_API_HOST $VITE_API_HOST

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/.output/ ./
