version: '3'

services:
  e2e:
    build: ./e2e
    ipc: host # Chrome can run out of memory without this
    environment:
      E2E_HOST: http://frontend:3000
      E2E_USERNAME: e2e
      E2E_PASSWORD: GreatPassword
      E2E_UNUSED_USERNAME: bad_e2e
      E2E_UNUSED_EMAIL: bad_e2e@example.com
    profiles:
      - e2e
    volumes:
      - ./e2e:/usr/src/e2e
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - /usr/src/app/node_modules/
      - ./frontend/:/usr/src/app/
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      SQL_HOST: db
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}

volumes:
  postgres_data:
