version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_HOST: ${VITE_API_HOST}
    volumes:
      - /usr/src/app/node_modules/
      - backend_static:/usr/src/app/static/
    ports:
      - 8000:80
    env_file:
      - ./.env
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn forum.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - backend_static:/usr/src/app/static/
    expose:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      SQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  backend_static:
