version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
      args:
        DOMAIN: ${DOMAIN}
        VERSION: ${VERSION}
        INTERNAL_FRONTEND_HOST: frontend
        INTERNAL_BACKEND_HOST: backend
        OTLP_HOST: ${OTLP_HOST}
        OTLP_TOKEN: ${OTLP_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - backend_static:/usr/src/app/static/
      - ./certbot/certs/:/etc/nginx/ssl/live/
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_HOST: http://backend:9000/be/
    command: node server/index.mjs
    volumes:
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
        AWS_CLOUDFRONT_DOMAIN: ${AWS_CLOUDFRONT_DOMAIN}
    command: opentelemetry-instrument gunicorn forum.wsgi:application --bind 0.0.0.0:9000 --access-logfile -
    volumes:
      - backend_static:/usr/src/app/static/
    ports:
      - 9000:9000
    env_file:
      - ./.env
    environment:
      SQL_HOST: db
      DJANGO_SETTINGS_MODULE: forum.settings
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  e2e:
    build: ./e2e
    ipc: host # Chrome can run out of memory without this
    env_file:
      - ./.env
    environment:
      E2E_HOST: https://nginx
    profiles:
      - e2e
    volumes:
      - ./e2e:/usr/src/e2e
    depends_on:
      - frontend

volumes:
  postgres_data:
  backend_static:
