#!/bin/sh -e

if [ ! -z $CI ]; then
    compose='docker compose -f compose.ci.yaml'
elif [ ! -z $PREVIEW ]; then
    compose='docker compose -f compose.preview.yaml'
else
    compose='docker compose'
fi

frontend_run() {
    $compose run --rm frontend $*
}

backend_run() {
    $compose run --rm backend $*
}

e2e_run() {
    $compose build e2e
    $compose run --rm e2e $*
}

lint() {
    frontend_run npm run lint
    frontend_run npm run typecheck
    backend_run python -m flake8
    backend_run python -m mypy .
    e2e_run python -m flake8
}

format() {
    frontend_run npm run format
    backend_run python -m black --line-length 79 .
    e2e_run python -m black --line-length 79 .
    terraform fmt infra
}

unit_test() {
    backend_run python -m pytest
    frontend_run npm run test -- --run
}

e2e() {
    backend_run python manage.py flush --no-input
    backend_run python manage.py seed
    e2e_run python -m pytest $*
}

install_local_e2e() {
    python -m venv env
    . env/bin/activate
    python -m pip install -r e2e/requirements.txt
    playwright install
}

load_env_file() {
    set -o allexport
    . ./.env
    set +o allexport
}

debug_e2e() {
    backend_run python manage.py flush --no-input
    backend_run python manage.py seed
    load_env_file
    . env/bin/activate
    cd e2e

    if [ ! -z $PREVIEW ]; then
        export E2E_HOST=http://localhost:8000
    else
        export E2E_HOST=http://localhost:3000
    fi

    PWDEBUG=1 python -m pytest $*
}

LOCAL_CERTS_DIR=certbot/certs/localhost
SSL_CERT=$LOCAL_CERTS_DIR/fullchain.pem
SSL_KEY=$LOCAL_CERTS_DIR/privkey.pem

generate_self_signed_cert() {
    mkdir -p $LOCAL_CERTS_DIR
    mkcert -install -cert-file $SSL_CERT -key-file $SSL_KEY localhost
}

dev() {
    if [ ! -z $PREVIEW ] && [ ! -f $SSL_CERT ]; then
        generate_self_signed_cert
        made_cert=true
    fi

    $compose up --build -d

    if [ ! -z $made_cert ]; then
        echo Generated a self-signed SSL certificate. >&2
        echo Certificate is in $SSL_CERT and key is in $SSL_KEY >&2
        echo -n If you did not already have the mkcert authority installed, >&2
        echo \ restart your >&2
        echo browser before accessing the site. >&2
        echo -n If you still get a security warning when visiting the site, >&2
        echo \ import the >&2
        echo certificate in your browser. >&2
    fi
}

if [ $# -eq 0 ]; then
    command=dev
else
    command=$1
    shift
fi

case $command in
    dev) dev ;; # Start the app for development
    restart) $compose down && dev ;; # Restart dev Docker containers
    lint) lint ;; # Check code for quality issues
    format) format ;; # Format source code
    test) unit_test ;; # Run unit tests
    migrate) backend_run python manage.py migrate ;; # Run database migrations
    pull) $compose pull && $compose pull e2e ;; # Pull Docker images
    e2e) e2e $* ;; # Run e2e specs
    build-e2e) $compose build e2e ;; # Build Docker image for e2e specs
    install-local-e2e) install_local_e2e ;; # Install e2e outside of Docker
    debug-e2e) debug_e2e $* ;; # Run local e2e with the Playwright Inspector
    stop) $compose down ;;
    rm) $compose down -v ;;
    *)
        echo "$0: Unrecognised command (see script for options): $command" >&2
        exit 1
        ;;
esac
