#!/bin/sh -e

frontend_run() {
    docker compose run --rm frontend $*
}

e2e_run() {
    docker compose build e2e
    docker compose run --rm e2e $*
}

lint() {
    frontend_run npm run lint
    frontend_run npm run typecheck
    e2e_run python -m flake8
}

format() {
    frontend_run npm run format
    e2e_run python -m black .
}

unit_test() {
    frontend_run npm run test -- --run
}

e2e() {
    e2e_run python -m pytest
}

dev() {
    docker compose up --build -d
}

if [ $# -gt 1 ]; then
    echo "Error: expected at most 1 command (see bottom of script for options)" >&2
    exit 1
elif [ $# -eq 0 ]; then
    command=dev
else
    command=$1
fi

case $command in
    dev) dev ;;
    restart) docker-compose down && dev ;;
    lint) lint ;;
    format) format ;;
    test) unit_test ;;
    e2e) e2e ;;
    stop) docker-compose down ;;
    rm) docker-compose down -v ;;
    *)
        echo "$0: Unrecognised command (see script for options): $command" >&2
        exit 1
        ;;
esac
