# Generated by Django 4.2.6 on 2023-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
