# Generated by Django 4.2.6 on 2023-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "light"), ("dark", "dark")], default="light"
            ),
        ),
    ]
