name: Deploy to prod
on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-prod:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend-prod:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend-prod:buildcache,mode=max
          build-args: |
            INTERNAL_BACKEND_HOST=forum_backend
            DOMAIN=${{ secrets.DOMAIN }}
            VITE_API_HOST=https://${{ secrets.DOMAIN }}/api/
      - name: Build backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-prod:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-prod:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-prod:buildcache,mode=max
