name: Build and test
on:
  push:
  workflow_dispatch:
env:
  CI: true
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init .env from .env.example
        run: cp .env.example .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend:buildcache,mode=max
      - name: Build backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend:buildcache,mode=max
      - name: Build e2e Docker image
        uses: docker/build-push-action@v5
        with:
          context: e2e
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/e2e:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/e2e:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/e2e:buildcache,mode=max
      - name: Pull images
        run: ./run pull
      - name: Lint code
        run: ./run lint
      - name: Run migrations
        run: ./run migrate
      - name: Run unit tests
        run: ./run test
      - name: Run e2e tests
        run: ./run e2e --video=retain-on-failure --screenshot=only-on-failure
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: e2e/test-results/
          retention-days: 7
